title: firehose
author: Dataloop.IO
version: 1.0.0
description: Dashboards and alert rules for Firehose streams monitored with the AWS integration
icon:
    name: firehose
    background: orange
    foreground: white
