title: kinesis
author: Dataloop.IO
version: 1.0.0
description: Dashboards and alert rules for kinesis monitored with the AWS integration
icon:
    name: kinesis
    background: orange
    foreground: white
