title: Apache2
author: Dataloop.IO
version: 1.0.3
processes:
    - apache2
    - httpd
description: Apache2 metrics from the mod-status module. Instructions contain configuration steps.
instructions_required: true
icon:
    name: apache
    background: "#DB3D7C"
    foreground: white

